### ISSUE TITLE
align() not working

### ISSUE THREAD

**Issue by nbarendt** [davidson16807/relativity.scad#11]
I'm trying basic examples from wiki, like

```
use <../relativity.scad/relativity.scad>;

box(50, anchor=[0,0,-1])
    align([0,0,1])
    sphere(d=60);
```

and get this

![image](https://cloud.githubusercontent.com/assets/156374/19025835/55fd07d4-88ec-11e6-9bf0-afac63b27c9c.png)

instead of this:

![image](https://raw.githubusercontent.com/davidson16807/relativity.scad/master/images/children2.png)

from the wiki.

I'm running OpenScad 2015.03 on OS X (10.11.6) and latest commit (6d5cc88) of 

https://github.com/davidson16807/relativity.scad 

Apologies if I'm missing something obvious.

**Comment by davidson16807** [comment]
Thank you for catching this. I've reproduced the issue. You'll need to use the "include" statement to work with the library: 

    include <../relativity.scad/relativity.scad>;

    box(50, anchor=[0,0,-1])
        align([0,0,1])
        sphere(d=60);

The "use" statement imports definitions without running anything. relativity.scad needs to run code in order to setup its environment. 

This was something I wasn't aware of. I'll make some edits to the wiki to make this point clear.

**Comment by nbarendt** [comment]
Ahh!  Thanks.  That makes sense (agree - putting a few complete examples in the wiki would help).

**Comment by davidson16807** [comment]
A section on installation was added to the start of the wiki, with a note about the include keyword. Let me know if you have other issues.
