### ISSUE TITLE
differed does not work

### ISSUE THREAD

**Issue by jdawgaz** [davidson16807/relativity.scad#13]
The following code on the wiki does not provide the desired result:

differed("hole") 
ball(50)  
orient([x,y,z])  
rod(d=25, h=55, $class="hole");

I am on osx Sierra (10.12.4), openscad (2017.08.03). Latest version on relativity.scad.

![rel1](https://user-images.githubusercontent.com/1466055/29647685-54adb63c-883f-11e7-8fb5-f1d4816019d7.png)

**Comment by davidson16807** [comment]
Have you tried building with F6?

**Comment by jdawgaz** [comment]
that worked, but doing an F5, it did not.
can't remember a time, that F5 preview & F6 view did not look alike. Why is
that? and is there a way to fix that?


--
Extra Ham Operator: K7AZJ
Registered Linux User: 275424
Raspberry Pi and Openscad developer


*The most exciting phrase to hear in science - the one that heralds new
discoveries - is not "Eureka!" but "That's funny...".*- Isaac. Asimov

**Comment by davidson16807** [comment]
`differed()` takes the difference between positive and negative spaces. If you don't specify the positive space, it defaults to whatever the children are. So that code takes the hole and subtracts it from the hole plus some other stuff. Subtracting a part by itself can produce this sort of behavior. 

The problem goes away if you set the positive space not to include the hole:

    differed("hole", "not(hole)")
    ball(50)
    orient([x,y,z])
    rod(d=25, h=55, $class="hole");

So maybe this is an issue with defaults? We could set positive space to be the negation of the negative space, if no default is provided.

**Comment by jdawgaz** [comment]
I changed to code to this, and it works (and looks as expected).

You could change the wiki to reflect what the code should be, or change the defaults, so that when we put the code (that I first posted, from the wiki), it looks and acts as expected.

thanks.

**Comment by aleung** [comment]
It's better to change the default positive selector to "not(<negative>)".
