### ISSUE TITLE
hide() does not work with default geometric primitives (cube, cylinder, sphere)

### ISSUE THREAD

**Issue by baxerus** [davidson16807/relativity.scad#6]
The "hide()" module does not work with the default geometric primitives (like cube, cylinder, sphere). These are still rendered. Also nearly every other module uses the "hide()" module, so the problem occurs very often!

I have no (good) idea how to fix this. Perhaps a variable only available in relativity.scad-modules that enables the hide()-module to identify non-relativity.scad-children and therefore not rendering the sub-tree? Would this work with single default transformation in between a sub-tree (like a normal translate() or what ever)?

**Comment by baxerus** [comment]
Sorry, code examples. Result should be the same (or not?).

Working:
`translated([40,40,40])
box(40, anchor=center);
`

Not working:
`translated([40,-40,40])
cube(40, center=true);
`

**Comment by davidson16807** [comment]
Sorry for being late, I've been out for two weeks. 

As it was designed, the CSG operations will only work with relativity.scad primitives. This is intended behavior, but I will reconsider this if there's a workable solution. 

Here's how it works now: the `hide()` module doesn't check for anything. It can't possibly check for anything, because OpenSCAD never lets it see anything having to do with its children. All it can do is set a variable that later gets read by its children. That variable tells the children whether they should render or not. 

So if a child never does anything with the variable, it will render by default. This is what happens with the OpenSCAD primitives.  

One idea I have been bouncing around is to move the variable checking behavior to its own module. This would allow you to use the OpenSCAD primitives, but you would have to remember to add the extra module:

    hide() class("foo") cube(40, center=true); 

Would this satisfy your use case?

**Comment by baxerus** [comment]
It isn't possible to traverse into children of children in OpenSCAD, isn't it? And setting the variable in also in all sub-sub-children?

OpenSCAD lacks some features actually 😞

You mean putting "class" into an own module (at least I understand your example like this).
A "hide()" before some sub modules isn't really a good idea (than you can simply comment them out)...

**Comment by baxerus** [comment]
Another thing.

How about putting the whole relativity.scad code into it's own root module? So the defined variables are less likely to interference with eventually already used names.
I sometimes import many libraries at the same time 😊

Like:
`relativity_root() hide() class("foo") cube(40, center=true); 
`

**Comment by davidson16807** [comment]
>It isn't possible to traverse into children of children in OpenSCAD, isn't it? 

oh, it's totally possible:

    for (i = [0 : $children-1]){
        children(i);
    }

The issue isn't traversing the list of children. The issue having the parent determine whether a specific child of the list should render. I'm pretty sure it can't be done that way.

"class()" is a working title for the function. I'm calling it that since I wanted to couple it with the ability to assign to the existing `$class` special variable. Another name might be "selectable()". All it does is check to see whether its children should render, then invoke `children()` if so.

Here's a first pass at the function:

    module class(name){
        _assign($class = name)
        _assign(
            $_ancestor_classes = _push($_ancestor_classes, 
                _tokenize($class, _token_regex_ignore_dash)
            )
        )
        if(_sizzle_engine($_ancestor_classes, $_show))  
            children();
    }

A thought just struck me: `hide()`  could add this `class()` module to its children automatically. This would address the immediate issue you raise:

    module hide_fixed(selector){
        hide(selector)
        for (i = [0 : $children-1]){
            class("")
            children(i);
        }
    }

    hide_fixed("*"){
        cube(100);
        sphere(100);
        box(150);
    }

However, an OpenSCAD primitive will still show if nested within a relativity primitive:

    hide_fixed("foo"){
        box(150, $class="foo")
        sphere(100);
    }

So that means the relativity primitives need to add `class()` to their children as well. However, class by default would set `$class = ""`, meaning a class ancestry like ["foo", "bar"] would change to ["foo", "", "bar"]. Selectors that use the ancestor operator would still work, e.g. "foo bar", but this change would break selectors that use the direct descendant operator, e.g. "foo>bar". However, this wouldn't be the case if `class()` doesn't also reassign to the value of `$class`. If we drop that functionality, a better name for `class()` would be something more like `selectable()` So I just talked myself out of calling it `class()` :)

>How about putting the whole relativity.scad code into it's own root module? So the defined variables are less likely to interference with eventually already used names.

Separate issue. That would require a breaking change. It maybe something to consider if there's another breaking change needed, say, for compatibility with the next version of OpenSCAD.

**Comment by davidson16807** [comment]
Actually, even if we tried to implement a namespace module, it's not apparent to me how we would go about doing that. You're trying to get a module to expose a set of other modules to its children. I don't believe OpenSCAD allows that.

**Comment by baxerus** [comment]
I don't know how to do it either. But that only some things work to primitives and other functionalities don't is a pity. I creates some sort of unpredictable behavior, that is not very nice!

> How about putting the whole relativity.scad code into it's own root module? So the defined variables are less likely to interference with eventually already used names.

> Separate issue. That would require a breaking change. It maybe something to consider if there's another breaking change needed, say, for compatibility with the next version of OpenSCAD.

😞 I would like to have the now global variables capsulated in a module scope, because of interferences. Perhaps later.

**Comment by davidson16807** [comment]
There should be a fix for the issue on the mainline. The fix does the following:

* create a new module, `selectable()`, as shown above
* wrap children in selectable for **primitives** and **CSG operators** 

I have not yet fully explored the consequences. Try it out and tell me if this suits your needs.

**Comment by davidson16807** [comment]
OK, issue #10 tells me that didn't work. I'll have to look into this further.

**Comment by baxerus** [comment]
Yes, perhaps a quick fix isn't possible.
Perhaps it's not possible at all.

But than, at least the documentation should mention more clearly that basic primitives could cause problems with the library and should be avoided (or even better replaced by the library's primitives).
But it's a pity for the drop-in-replacement-ability😞

What do you think?

**Comment by gadgetmind** [comment]
I'm doing this, it works, and it's awesome. Just lashed up proof of concept for now but I'm going to be using this for all of my objects with fastener holes.

module DrawBox () {
	v = roundbox_v(dx,dy,dz,rx,ry,rz,fn,nx,ny,nz);
	polyhedron(v[0],v[1]);
}

module DrilledBox () {
	class ("positive") DrawBox ();
	translate ([0, 0, BracketLen/2+Tad]) rotate ([0, 0, 0])
	class("hole") {
		hole_through(name="M3", l=BracketLen+Tad2);
		nutcatch_parallel(name="M3", clk=0.1);
	}
}

**Comment by davidson16807** [comment]
Thanks for everybody's patience. @aleung put out a PR a while ago that I just got around to reviewing, commit fd1b36 adds the `class()` module that @gadgetmind mentioned working with. Previously when I last implemented `selectable()` I was intending for it to serve as the functionality underlying every other relativity primitive (box, ball, rod, etc). It didn't work out to that capacity but I suppose that doesn't stop it from being useful in more limited contexts, so by popular demand here it is. I'll close the issue but feel free to post more if issues arise with the existing `class()` implementation
